### ISSUE TITLE
in pre-release, none of the setting dropdowns work

### ISSUE THREAD

**Issue by RustoMCSpit** [ShacharHarshuv/open-ear#227]

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit Can you please add more information to this ticket?
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by RustoMCSpit** [comment]
Uploading GithubFile.mp4…

**Comment by RustoMCSpit** [comment]
https://github.com/ShacharHarshuv/open-ear/assets/134429563/829e9955-3e91-4f10-b008-75ae1369367c

**Comment by ShacharHarshuv** [comment]
For some reason I remember this bug was fixed and deployed...

**Comment by entomologe** [comment]
I can reproduce this bug. I'm on version 1.2.6 if that helps.

@ShacharHarshuv - thanks btw.: this is an awesome program and I'm looking forward to support it in the future. I already told 5 people about it. 😃

**Comment by ShacharHarshuv** [comment]
That's on older version. First thing I would try is to see if you can update it via the store. 
Are you using iOS? I was having issues with releasing new versions in iOS so it might be related.

**Comment by entomologe** [comment]
> That's on older version. First thing I would try is to see if you can update it via the store. Are you using iOS? I was having issues with releasing new versions in iOS so it might be related.

Ohh, pardon me, I assumed F-Droid packed the latest. I tried now 1.5.7 and although it's great how much there was added, dropdown still doesn't work for me (Android 14).

**Comment by entomologe** [comment]
> > That's on older version. First thing I would try is to see if you can update it via the store. Are you using iOS? I was having issues with releasing new versions in iOS so it might be related.
> 
> Ohh, pardon me, I assumed F-Droid packed the latest. I tried now 1.5.7 and although it's great how much there was added, dropdown still doesn't work for me (Android 14).

I just tried the version from the play store and problem is gone. I happened to test the apk which was a lot smaller, so I assume there is more bundled in the one from the playstore?

**Comment by ShacharHarshuv** [comment]
The F-Droid release is not managed be, it was built and uploaded by a community member independently, so it's entirely possible that not only it's not maintained, but that something went wrong with the build. 

I'm glad you were able to solve the issue by downloading it from the store. 

Should we close this issue?

**Comment by entomologe** [comment]
> The F-Droid release is not managed be, it was built and uploaded by a community member independently, so it's entirely possible that not only it's not maintained, but that something went wrong with the build.

I'll maybe look into it furthermore.
 
> I'm glad you were able to solve the issue by downloading it from the store.

Thank you very much for the help.

> Should we close this issue?

Yes, I'd think so.
